// Code generated by go-swagger; DO NOT EDIT.

package mantan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"ngajarinlinda/gen/models"
)

// GetMantanByNameReader is a Reader for the GetMantanByName structure.
type GetMantanByNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMantanByNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetMantanByNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetMantanByNameInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/mantan/{nama_mantan}] getMantanByName", response, response.Code())
	}
}

// NewGetMantanByNameOK creates a GetMantanByNameOK with default headers values
func NewGetMantanByNameOK() *GetMantanByNameOK {
	return &GetMantanByNameOK{}
}

/*
GetMantanByNameOK describes a response with status code 200, with default header values.

return list of mantans
*/
type GetMantanByNameOK struct {
	Payload []*models.Mantan
}

// IsSuccess returns true when this get mantan by name o k response has a 2xx status code
func (o *GetMantanByNameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get mantan by name o k response has a 3xx status code
func (o *GetMantanByNameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get mantan by name o k response has a 4xx status code
func (o *GetMantanByNameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get mantan by name o k response has a 5xx status code
func (o *GetMantanByNameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get mantan by name o k response a status code equal to that given
func (o *GetMantanByNameOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get mantan by name o k response
func (o *GetMantanByNameOK) Code() int {
	return 200
}

func (o *GetMantanByNameOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/mantan/{nama_mantan}][%d] getMantanByNameOK  %+v", 200, o.Payload)
}

func (o *GetMantanByNameOK) String() string {
	return fmt.Sprintf("[GET /api/v1/mantan/{nama_mantan}][%d] getMantanByNameOK  %+v", 200, o.Payload)
}

func (o *GetMantanByNameOK) GetPayload() []*models.Mantan {
	return o.Payload
}

func (o *GetMantanByNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMantanByNameInternalServerError creates a GetMantanByNameInternalServerError with default headers values
func NewGetMantanByNameInternalServerError() *GetMantanByNameInternalServerError {
	return &GetMantanByNameInternalServerError{}
}

/*
GetMantanByNameInternalServerError describes a response with status code 500, with default header values.

server error
*/
type GetMantanByNameInternalServerError struct {
	Payload *GetMantanByNameInternalServerErrorBody
}

// IsSuccess returns true when this get mantan by name internal server error response has a 2xx status code
func (o *GetMantanByNameInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get mantan by name internal server error response has a 3xx status code
func (o *GetMantanByNameInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get mantan by name internal server error response has a 4xx status code
func (o *GetMantanByNameInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get mantan by name internal server error response has a 5xx status code
func (o *GetMantanByNameInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get mantan by name internal server error response a status code equal to that given
func (o *GetMantanByNameInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get mantan by name internal server error response
func (o *GetMantanByNameInternalServerError) Code() int {
	return 500
}

func (o *GetMantanByNameInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v1/mantan/{nama_mantan}][%d] getMantanByNameInternalServerError  %+v", 500, o.Payload)
}

func (o *GetMantanByNameInternalServerError) String() string {
	return fmt.Sprintf("[GET /api/v1/mantan/{nama_mantan}][%d] getMantanByNameInternalServerError  %+v", 500, o.Payload)
}

func (o *GetMantanByNameInternalServerError) GetPayload() *GetMantanByNameInternalServerErrorBody {
	return o.Payload
}

func (o *GetMantanByNameInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetMantanByNameInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
GetMantanByNameInternalServerErrorBody get mantan by name internal server error body
swagger:model GetMantanByNameInternalServerErrorBody
*/
type GetMantanByNameInternalServerErrorBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this get mantan by name internal server error body
func (o *GetMantanByNameInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get mantan by name internal server error body based on context it is used
func (o *GetMantanByNameInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetMantanByNameInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetMantanByNameInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res GetMantanByNameInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
