// Code generated by go-swagger; DO NOT EDIT.

package mantan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetMantanByNameParams creates a new GetMantanByNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetMantanByNameParams() *GetMantanByNameParams {
	return &GetMantanByNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetMantanByNameParamsWithTimeout creates a new GetMantanByNameParams object
// with the ability to set a timeout on a request.
func NewGetMantanByNameParamsWithTimeout(timeout time.Duration) *GetMantanByNameParams {
	return &GetMantanByNameParams{
		timeout: timeout,
	}
}

// NewGetMantanByNameParamsWithContext creates a new GetMantanByNameParams object
// with the ability to set a context for a request.
func NewGetMantanByNameParamsWithContext(ctx context.Context) *GetMantanByNameParams {
	return &GetMantanByNameParams{
		Context: ctx,
	}
}

// NewGetMantanByNameParamsWithHTTPClient creates a new GetMantanByNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetMantanByNameParamsWithHTTPClient(client *http.Client) *GetMantanByNameParams {
	return &GetMantanByNameParams{
		HTTPClient: client,
	}
}

/*
GetMantanByNameParams contains all the parameters to send to the API endpoint

	for the get mantan by name operation.

	Typically these are written to a http.Request.
*/
type GetMantanByNameParams struct {

	// NamaMantan.
	NamaMantan string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get mantan by name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMantanByNameParams) WithDefaults() *GetMantanByNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get mantan by name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMantanByNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get mantan by name params
func (o *GetMantanByNameParams) WithTimeout(timeout time.Duration) *GetMantanByNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get mantan by name params
func (o *GetMantanByNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get mantan by name params
func (o *GetMantanByNameParams) WithContext(ctx context.Context) *GetMantanByNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get mantan by name params
func (o *GetMantanByNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get mantan by name params
func (o *GetMantanByNameParams) WithHTTPClient(client *http.Client) *GetMantanByNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get mantan by name params
func (o *GetMantanByNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNamaMantan adds the namaMantan to the get mantan by name params
func (o *GetMantanByNameParams) WithNamaMantan(namaMantan string) *GetMantanByNameParams {
	o.SetNamaMantan(namaMantan)
	return o
}

// SetNamaMantan adds the namaMantan to the get mantan by name params
func (o *GetMantanByNameParams) SetNamaMantan(namaMantan string) {
	o.NamaMantan = namaMantan
}

// WriteToRequest writes these params to a swagger request
func (o *GetMantanByNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param nama_mantan
	if err := r.SetPathParam("nama_mantan", o.NamaMantan); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
