// Code generated by go-swagger; DO NOT EDIT.

package mantan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new mantan API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for mantan API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetAllMantan(params *GetAllMantanParams, opts ...ClientOption) (*GetAllMantanOK, error)

	GetMantanByName(params *GetMantanByNameParams, opts ...ClientOption) (*GetMantanByNameOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
GetAllMantan ngelists semua mantan

ngelist semua mantan haha
*/
func (a *Client) GetAllMantan(params *GetAllMantanParams, opts ...ClientOption) (*GetAllMantanOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetAllMantanParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getAllMantan",
		Method:             "GET",
		PathPattern:        "/api/v1/mantan",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAllMantanReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetAllMantanOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getAllMantan: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetMantanByName ngelists semua mantan

ngelist semua mantan haha
*/
func (a *Client) GetMantanByName(params *GetMantanByNameParams, opts ...ClientOption) (*GetMantanByNameOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetMantanByNameParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getMantanByName",
		Method:             "GET",
		PathPattern:        "/api/v1/mantan/{nama_mantan}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetMantanByNameReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetMantanByNameOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getMantanByName: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
