consumes:
    - application/json
info:
    description: Project ngajarin linda
    title: Ngajarin Linda
    version: 1.0.0
produces:
    - application/json
schemes:
    - http
swagger: "2.0"

paths:
    /api/v1/mantan:
      get:
        tags:
          - mantan
        summary: "ngelist semua mantan"
        description: "ngelist semua mantan haha"
        operationId: getAllMantan
        security: []
        responses:
            200:
                description: "return list of mantans"
                schema:
                  type: array
                  items:
                    $ref: "#/definitions/Mantan"
            500:
                description: server error 
                schema:
                    type: object
                    properties:
                      message:
                        type: string
                        
    /api/v1/mantan/{nama_mantan}:
      get:
        tags:
          - mantan
        summary: "ngelist semua mantan"
        description: "ngelist semua mantan haha"
        operationId: getMantanByName
        security: []
        parameters:
          - name: nama_mantan
            in: path
            type: string
            required: true
        responses:
            200:
                description: "return list of mantans"
                schema:
                  type: array
                  items:
                    $ref: "#/definitions/Mantan"
            500:
                description: server error 
                schema:
                    type: object
                    properties:
                      message:
                        type: string
                        
definitions:
    ModelTrackTime:
      type: object
      properties:
        created_at:
          type: integer
          format: date-time
          x-omitempty: false
          x-go-custom-tag: gorm:"type:int;autoCreateTime"
        updated_at:
          type: integer
          format: date-time
          x-omitempty: false
          x-go-custom-tag: gorm:"type:int;autoUpdateTime"

    ModelIdentifier:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: uint64
          x-go-custom-tag: gorm:"type:int auto_increment;primaryKey"

    Mantan:
      allOf:
        - $ref: "#/definitions/ModelTrackTime"
        - $ref: "#/definitions/ModelIdentifier"
        - type: object
          properties:
            nama:
              type: string
            umur:
              type: integer
            status:
              type: string
              enum: [single,married]
        
          
          


